name       : xpad
version    : 5.4.0
release    : 3
source     :
    - https://launchpad.net/xpad/trunk/5.4.0/+download/xpad-5.4.0.tar.bz2 : a395cb282a2cfb0d56f1e911afb7e38ad74f6d738082a7c6c181b3052ca7f5e2
license    : GPL-2.0-only
component  : office.notes
summary    : A basic sticky note application
description: |
    A sticky note application for jotting down things to remember
builddeps  :
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(xt)
setup      : |
    NOCONFIGURE=1 %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
