name       : xpad
version    : 5.0.0
release    : 1
source     :
    - https://launchpad.net/xpad/trunk/5.0.0/+download/xpad-5.0.0.tar.bz2 : 6b5673c68faad4afb44aea0ff5d72c7b5d2aef0d00a89980a27ca56f5e9fd10b
license    : GPL-2.0-only
component  : office.notes
summary    : A basic sticky note application
description: |
    A sticky note application for jotting down things to remember
builddeps  :
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(xt)
setup      : |
    %autogen    
    %configure
build      : |
    %make
install    : |
    %make_install
